baseURL: 'https://rprtr258.github.io/'
languageCode: 'en-us'
title: 'rprtr258'
theme: "PaperMod"
publishDir: build
params:
  hideFooter: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  homeInfoParams:
    Title: Hello, world!
    Content: >
      # rprtr258 here
  socialIcons:
    - name: Twitch
      url: https://www.twitch.tv/rprtr258
    - name: Github
      url: https://github.com/rprtr258
    - name: Steam
      url: https://steamcommunity.com/id/rprtr258
    - name: Deviantart
      url: https://www.deviantart.com/rprtr258
    - name: facebook
      url: https://vk.com/rprtr258
    - name: facebook
      url: https://vk.com/id168715495
    - name: telegram
      url: https://t.me/rprtr258
    - name: spotify
      url: https://open.spotify.com/user/21xgcujwwcwy3ak5xii4js6hy
    - name: kaggle
      url: https://www.kaggle.com/rprtr258
    - name: acmp
      url: https://acmp.ru/index.asp?main=user&amp;id=1191
    - name: klavogonki
      url: http://klavogonki.ru/u/#/40092
    - name: osu
      url: https://osu.ppy.sh/users/8914558
    - name: reddit
      url: https://www.reddit.com/user/rprtr258/
    - name: lichess
      url: https://lichess.org/@/rprtr258
    - name: e-olymp
      url: https://www.e-olymp.com/ru/users/rprtr258
    - name: CodeChef
      url: https://www.codechef.com/users/rprtr258
    - name: Codeforces
      url: https://codeforces.com/profile/rprtr258
    - name: A2 Online Judge
      url: https://a2oj.com/profile?Username=rprtr258
    - name: discord
      url: https://discordapp.com/users/7003
menu:
  main:
    - identifier: watch_list
      name: Watch list
      url: /watch_list/
      weight: 10
    - identifier: cv
      name: CV
      url: /cv/
      weight: 20
    - identifier: menhera
      name: Menhera chan
      url: /menhera/
      weight: 30
    - identifier: mmheroes
      name: MMHeroes
      url: /mmheroes/
      weight: 40
    - identifier: utils
      name: Utils (18+)
      url: /utils/
      weight: 50
