name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Jekyll
        uses: ConorMacBride/install-package@v1.0.0
        with:
          apt: jekyll

      - name: Jekyll build
        run: |
          jekyll build
          mv build /tmp/build
  
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: aboba
        run: |
          rm -rf *
          mv /tmp/build/* .

      - name: Github commit and push
        uses: Smart-Transportation/push@v1.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          message: ABOBUS
          branch: gh-pages
          empty: true
          
