name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
          check-latest: true

      - name: Install deps
        run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-table-reader-plugin

      - name: Build
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
