name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          target_branch: 'gh-pages'
