name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create build directory
        run: 
          sudo apt install jekyll
          jekyll build
          mv build /tmp/build
          git checkout gh-pages
          mv /tmp/build/* .
          git add *
          git commit -am "Autoupdate"
          git push
